title: Shuai Ruan's Blogging
description: "A Blogging for Shuai Ruan! Happy Birthday!2019-06-18"
author:
  name: "ruanshuai"
  email: "rsow001@gmail.com"
  url: "https://orange2008.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "ruanshuai"
year : "2019"

theme: jekyll-theme-hacker